import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-functions.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig); const auth=getAuth(app); const functions=getFunctions(app); const $=id=>document.getElementById(id); const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#039;"}[c])); const money=n=>`Rs. ${Number(n||0).toLocaleString("en-PK",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function toast(msg,error=false){const el=$("toast");el.textContent=msg;el.className=`toast show${error?" error":""}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.className="toast",3000)}
const call=async(name,data={})=>(await httpsCallable(functions,name)(data)).data;
$("adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("adminEmail").value.trim(),$("adminPassword").value);toast("Signed in")}catch(err){toast(err.message||"Login failed",true)}});
$("adminLogoutBtn").addEventListener("click",()=>signOut(auth)); $("refreshBtn").addEventListener("click",()=>loadDashboard().catch(()=>{}));
$("saveSettingsBtn").addEventListener("click",async()=>{try{const s={usdtPkrRate:Number($("setRate").value),tradingFeePct:Number($("setFee").value),minBuyPkr:Number($("setMinBuy").value),maxBuyPkr:Number($("setMaxBuy").value),referralBonusPct:Number($("setReferralPct").value),referralBonusCapPkr:Number($("setReferralCap").value)};await call("adminUpdateSettings",s);toast("Settings saved");loadDashboard()}catch(e){toast(e.message||"Could not save settings",true)}});
$("userFilter").addEventListener("input",()=>renderUsers(window.__users||{}));
async function loadDashboard(){try{const d=await call("adminGetDashboard");window.__dashboard=d;window.__users=d.users||{};$("mUsers").textContent=Object.keys(d.users||{}).length;$("mDeposits").textContent=(d.pendingDeposits||[]).length;$("mWithdrawals").textContent=(d.pendingWithdrawals||[]).length;$("mRate").textContent=money(d.settings?.usdtPkrRate);$("setRate").value=d.settings?.usdtPkrRate??280;$("setFee").value=d.settings?.tradingFeePct??0.5;$("setMinBuy").value=d.settings?.minBuyPkr??100;$("setMaxBuy").value=d.settings?.maxBuyPkr??100000;$("setReferralPct").value=d.settings?.referralBonusPct??1;$("setReferralCap").value=d.settings?.referralBonusCapPkr??500;renderDeposits(d.pendingDeposits||[]);renderWithdrawals(d.pendingWithdrawals||[]);renderUsers(d.users||{})}catch(e){toast(e.message||"Admin access denied",true);throw e}}
function renderDeposits(rows){$("depositAdminList").innerHTML=rows.length?rows.map(x=>`<div class="admin-item"><div class="meta"><strong>${safe(x.name||x.email||x.uid)} • ${money(x.amountPkr)}</strong><span class="muted">${safe(x.method)} • ${safe(x.account)} • Ref: ${safe(x.txnId)}</span><span class="muted">${new Date(x.createdAt||Date.now()).toLocaleString("en-PK")}</span></div><div class="admin-actions"><button class="btn primary small" data-dep-act="approve" data-id="${safe(x.requestId)}">Approve</button><button class="btn warning small" data-dep-act="reject" data-id="${safe(x.requestId)}">Reject</button></div></div>`).join(""):'<div class="muted">No pending deposits.</div>';$("depositAdminList").querySelectorAll("[data-dep-act]").forEach(b=>b.addEventListener("click",()=>processDeposit(b.dataset.id,b.dataset.depAct)));}
async function processDeposit(id,action){try{await call("adminProcessDeposit",{requestId:id,action});toast(`Deposit ${action}d`);loadDashboard()}catch(e){toast(e.message||"Request failed",true)}}
function renderWithdrawals(rows){$("withdrawAdminList").innerHTML=rows.length?rows.map(x=>`<div class="admin-item"><div class="meta"><strong>${safe(x.name||x.email||x.uid)} • ${money(x.amountPkr)}</strong><span class="muted">${safe(x.method)} • ${safe(x.account)} • Holder: ${safe(x.holder)}</span><span class="muted">${new Date(x.createdAt||Date.now()).toLocaleString("en-PK")}</span></div><div class="admin-actions"><a class="btn ghost small" target="_blank" rel="noopener" href="https://wa.me/923423944508?text=${encodeURIComponent(`CoinVault withdrawal request\nUser: ${x.name||x.email}\nAmount: ${money(x.amountPkr)}\nMethod: ${x.method}\nAccount: ${x.account}\nHolder: ${x.holder}\nRequest: ${x.requestId}`)}">WhatsApp</a><button class="btn primary small" data-wd-act="approve" data-id="${safe(x.requestId)}">Approve</button><button class="btn warning small" data-wd-act="reject" data-id="${safe(x.requestId)}">Reject / Refund</button></div></div>`).join(""):'<div class="muted">No pending withdrawals.</div>';$("withdrawAdminList").querySelectorAll("[data-wd-act]").forEach(b=>b.addEventListener("click",()=>processWithdrawal(b.dataset.id,b.dataset.wdAct)));}
async function processWithdrawal(id,action){try{await call("adminProcessWithdrawal",{requestId:id,action});toast(`Withdrawal ${action}d`);loadDashboard()}catch(e){toast(e.message||"Request failed",true)}}
function renderUsers(users){const q=$("userFilter").value.trim().toLowerCase();const rows=Object.entries(users).filter(([uid,u])=>!q||`${uid} ${u.name||""} ${u.email||""} ${u.phone||""}`.toLowerCase().includes(q)).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0));$("userAdminList").innerHTML=rows.map(([uid,u])=>`<div class="admin-item"><div class="meta"><strong>${safe(u.name||u.email||uid)}</strong><span class="muted">${safe(u.email||"")} • ${safe(u.phone||"")}</span><span class="muted">UID: ${safe(uid)}</span></div><div class="admin-actions"><span class="btn ghost small">${money(window.__dashboard.wallets?.[uid]?.cashBalancePkr||0)}</span></div></div>`).join("")||'<div class="muted">No matching users.</div>';}
onAuthStateChanged(auth,async user=>{if(!user){$("adminAuth").classList.remove("hidden");$("adminView").classList.add("hidden");return;}try{await loadDashboard();$("adminAuth").classList.add("hidden");$("adminView").classList.remove("hidden")}catch(e){toast(e.message||"Not an admin",true);await signOut(auth)}});
